### ISSUE TITLE
Fresh ML library from the master branch 

### ISSUE THREAD

**Issue by pindash** [KxSystems/ml#5]
.ml.fresh.significantfeatures is broken.

the function is trying to pull columns from a table using #(take) notation, this is incorrect and will fail, you can do this from a dictionary, but I would recommend using applicative notation. 

Here is original and suggested changes after making these changes the function started working, 
0riginal:
fresh.significantfeatures:{[table;targets]
 table:(where 0=var each flip table)_table;
 bintest:{2=count distinct x};
 bintarget:bintest targets;
 bincols:where bintest each flip table;
 realcols:cols[table]except bincols;
 bintab:bincols#table;
 realtab:realcols#table;
 pvals:raze$[bintarget;
         {y[x;]each flip z}[targets]'[fresh.ks2samp,fresh.fishertest;(realtab;bintab)];
         {y[x;]each flip z}[targets]'[fresh.ktaupy,fresh.ks2samp;(realtab;bintab)]];
 insignificant:fresh.benjhochfind[pvals;0.05];
 cols[table]except insignificant
 }

suggested changes:
fresh.significantfeatures:{[table;targets]
 table:(where 0=var each flip table)_table;
 bintest:{2=count distinct x};
 bintarget:bintest targets;
 bincols:where bintest each flip table;
 realcols:cols[table]except bincols;
 **bintab:table[bincols];**
 **realtab:table[realcols];**
 pvals:raze$[bintarget;
         **{y[x;]each z}[targets]'[fresh.ks2samp,fresh.fishertest;(realtab;bintab)];**
         **{y[x;]each z}[targets]'[fresh.ktaupy,fresh.ks2samp;(realtab;bintab)]];**
 insignificant:fresh.benjhochfind[pvals;0.05];
  **cols[table]except cols[table]insignificant**  
 }

**Comment by cmccarthy1** [comment]
Hi Pindash,

Thanks for the message, the function is actually doings as it's designed to from what I can see, the take function in the form `x#y` where x is a list of symbols and y is an unkeyed table will return an un-keyed table containing the subset of columns `x` from y as in the below example.

```
q)5#table:([]100?0b;100?1f;100?0b;100?1f)
x         x1 x2         x3
--------------------------
0.7433285 0  0.8481567  0 
0.2371288 1  0.389056   1 
0.567081  1  0.391543   1 
0.4269177 1  0.08123546 0 
0.7704774 0  0.9367503  0 
q)binaryfunc:{2=count distinct x}       /find where columns contain only 'binary' data
q)show binarycols:where binaryfunc each flip table
`x1`x3
q)5#binarytab:binarycols#table
x1 x3
-----
0  0 
1  1 
1  1 
1  0 
0  0 
```

This is outlined at https://code.kx.com/q/ref/lists/#take . If you can provide a specific edge case where you have experienced this I'll be more than happy to take a look at it and add in a fix.

Kind regards,

Conor

**Comment by pindash** [comment]
Perhaps its my version of Kdb I'm using 3.6 and I agree that's what is
supposed to happen but the function definitely failed when I tried it. just
pull the master branch and load the code up and use the example code from
the documentation at http://code.kx.com/ml/toolkit/fresh/

I just went home for the day, but will double check tomorrow morning. I may
have made some mistake

**Comment by cmccarthy1** [comment]
Yeah if you could rerun in the morning that would be great, I'm just after cloning from the git and rerunning the example that's in on code.kx (first running the feature creation section followed by the feature significance section below it) with out any issues. I'm also running 3.6 on Mac but it's also been tested on windows and linux machines.

Let me know what you find tomorrow.

All the best

**Comment by pindash** [comment]
Hey so I tested again today and it still fails:
![image](https://user-images.githubusercontent.com/2152033/49895720-30256b00-fe1f-11e8-9061-68fcd389e59b.png)

Here is sample code to reproduce:
\l ml/ml.q
.ml.loadfile`:fresh/init.q
t:flip `absenergy_orderSize`abssumchange_orderSize`count_orderSize!(4 625 2116 1 4 1 1 10000 10000 6290064f;0 0 0 0 0 0 0 0 0 0f;1 1 1 1 1 1 1 1 1 1)
tgt:enlist each 108.3051 108.3051 108.3051 108.3051 108.3051 108.3051 108.3051 108.3051 108.3051 108.3051
.ml.fresh.significantfeatures[t;tgt]

**Comment by pindash** [comment]
That's fair. But using the functional changes I provided allows those cases
to all work and the code can be shorter and has fewer flips.  So I think
it's a net win, your call.

**Comment by cmccarthy1** [comment]
I've now modified the code to take in your changes. Thanks for highlighting the issue!

**Comment by pindash** [comment]
Thank you
